apiVersions: v1
kind: Deployment
metadata:
  name: webtaller-deployment
  namespace: ptaller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtaller
  template:
    metadata:
      labels:
        app: webtaller
    spec:
      containers:
      - name: webtaller
        image: matiasgracia/webtaller:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: webtaller-config
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"