apiVersion: apps/v1
kind: Deployment
metadata:
  name: miportfolio-deployment
  namespace: miportfoliohelm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      containers:
        - name: miportfolio
          image: kuklusklan/miportfolio
          ports:
            - containerPort: 80