app:
  name: miportfolio
  image: 
    repository: kuklusklan/miportfolio
    tag: latest
    pullPolicy: Always
  container:
    name: miportfolio
    port: 80
    replicaCount: 3
  service :
    port: 80
    nodePort: 30003
  ingress:
    host: matias.megacrossover.net